numbers = [3, 1, 5]
numbers.append(7)
print("append:", numbers)
numbers.extend([2, 4])
print("extend:", numbers)
numbers.insert(1, 10)
print("insert:", numbers)
numbers.remove(10)
print("remove:", numbers)
numbers.sort()
print("sort:", numbers)
numbers.reverse()
print("reverse:", numbers)
new_numbers = numbers.copy()
print("copy:", new_numbers)
numbers.clear()
print("clear:", numbers)