text = input("Enter a string: ")
print("strip():", text.strip())
print("capitalize():", text.capitalize())
print("title():", text.title())
print("upper():", text.upper())
print("lower():", text.lower())